import type { PatientCase } from "./types";

const seedTimestamp = "2026-05-28T12:00:00.000Z";

export const seedPatients: PatientCase[] = [
  {
    id: "PAC-104",
    patient: {
      recordNumber: "PAC-104",
      fullName: "María Sosa",
      location: "Centro Norte",
    },
    modelInput: {
      age: 57,
      sex: "F",
      chestPainType: "NAP",
      restingBP: 132,
      cholesterol: 226,
      fastingBS: 0,
      maxHR: 148,
      exerciseAngina: "No",
      oldpeak: 0.4,
      restingECG: "Normal",
      stSlope: "Up",
    },
    workflow: {
      status: "Pendiente de triaje",
      nextRole: "enfermeria",
      currentTask: "Registrar mediciones iniciales y confirmar el ingreso del caso.",
      primaryActionLabel: "Completar triaje",
      timeline: [
        {
          id: "evt-pac-104-1",
          title: "Caso creado",
          by: "Recepción",
          note: "Se abrió un caso preventivo por controles regulares.",
          completed: true,
          timestamp: seedTimestamp,
        },
        {
          id: "evt-pac-104-2",
          title: "Carga de triaje",
          by: "Enfermería",
          note: "Faltan completar mediciones y confirmar el set de datos.",
          completed: false,
          timestamp: seedTimestamp,
        },
        {
          id: "evt-pac-104-3",
          title: "Evaluación médica",
          by: "Médico general",
          note: "Bloqueada hasta confirmar el triaje.",
          completed: false,
          timestamp: seedTimestamp,
        },
      ],
    },
    assessment: {
      riskLevel: "Medio",
      riskProbability: 0.42,
      clinicalSummary: "Paciente con fatiga y dolor no anginal. Falta completar mediciones.",
      topFactors: [
        "Faltan mediciones clínicas para completar la evaluación.",
        "Dolor de pecho no anginal.",
      ],
    },
    metadata: {
      createdAt: seedTimestamp,
      updatedAt: seedTimestamp,
    },
  },
  {
    id: "PAC-271",
    patient: {
      recordNumber: "PAC-271",
      fullName: "Jorge Ferreyra",
      location: "Policlínico Oeste",
    },
    modelInput: {
      age: 63,
      sex: "M",
      chestPainType: "ASY",
      restingBP: 145,
      cholesterol: 289,
      fastingBS: 1,
      maxHR: 118,
      exerciseAngina: "Sí",
      oldpeak: 1.8,
      restingECG: "ST",
      stSlope: "Flat",
    },
    workflow: {
      status: "Listo para evaluación",
      nextRole: "medico",
      currentTask: "Calcular el riesgo y decidir si corresponde derivación o cierre clínico.",
      primaryActionLabel: "Registrar conducta",
      timeline: [
        {
          id: "evt-pac-271-1",
          title: "Datos iniciales confirmados",
          by: "Enfermería",
          note: "Todas las mediciones necesarias quedaron registradas.",
          completed: true,
          timestamp: seedTimestamp,
        },
        {
          id: "evt-pac-271-2",
          title: "Pendiente de score",
          by: "Médico general",
          note: "La app espera la evaluación apoyada por el modelo.",
          completed: false,
          timestamp: seedTimestamp,
        },
        {
          id: "evt-pac-271-3",
          title: "Derivación",
          by: "Cardiología",
          note: "Todavía no iniciada.",
          completed: false,
          timestamp: seedTimestamp,
        },
      ],
    },
    assessment: {
      riskLevel: "Alto",
      riskProbability: 0.86,
      clinicalSummary:
        "Caso preparado para consulta médica con factores de riesgo combinados.",
      topFactors: [
        "Dolor de pecho asintomático.",
        "Glucemia en ayunas por encima de 120 mg/dl.",
        "Angina inducida por ejercicio.",
        "Pendiente ST plana.",
      ],
    },
    metadata: {
      createdAt: seedTimestamp,
      updatedAt: seedTimestamp,
    },
  },
  {
    id: "PAC-318",
    patient: {
      recordNumber: "PAC-318",
      fullName: "Elena Acosta",
      location: "Clínica Sur",
    },
    modelInput: {
      age: 68,
      sex: "F",
      chestPainType: "ATA",
      restingBP: 138,
      cholesterol: 241,
      fastingBS: 1,
      maxHR: 126,
      exerciseAngina: "Sí",
      oldpeak: 2.1,
      restingECG: "LVH",
      stSlope: "Flat",
    },
    workflow: {
      status: "Derivado a cardiología",
      nextRole: "cardiologia",
      currentTask: "Revisar el score y registrar la resolución clínica final.",
      primaryActionLabel: "Registrar resolución",
      timeline: [
        {
          id: "evt-pac-318-1",
          title: "Triaje completado",
          by: "Enfermería",
          note: "Registro inicial validado.",
          completed: true,
          timestamp: seedTimestamp,
        },
        {
          id: "evt-pac-318-2",
          title: "Riesgo alto detectado",
          by: "Médico general",
          note: "Se deriva a cardiología con score y explicación.",
          completed: true,
          timestamp: seedTimestamp,
        },
        {
          id: "evt-pac-318-3",
          title: "Consulta especializada",
          by: "Cardiología",
          note: "Pendiente de resolución.",
          completed: false,
          timestamp: seedTimestamp,
        },
      ],
    },
    assessment: {
      riskLevel: "Alto",
      riskProbability: 0.79,
      clinicalSummary:
        "Paciente ya priorizada y esperando confirmación del especialista.",
      topFactors: [
        "Glucemia en ayunas elevada.",
        "Angina por ejercicio.",
        "ECG con hipertrofia ventricular izquierda.",
      ],
      hasHeartDisease: true,
      finalDiagnosis: "Enfermedad coronaria estable de alto riesgo.",
      specialistNotes:
        "Se confirma la necesidad de manejo especializado y cierre con indicaciones.",
    },
    metadata: {
      createdAt: seedTimestamp,
      updatedAt: seedTimestamp,
    },
  },
  {
    id: "PAC-402",
    patient: {
      recordNumber: "PAC-402",
      fullName: "Ricardo Vega",
      location: "Hospital Central",
    },
    modelInput: {
      age: 52,
      sex: "M",
      chestPainType: "TA",
      restingBP: 124,
      cholesterol: 198,
      fastingBS: 0,
      maxHR: 162,
      exerciseAngina: "No",
      oldpeak: 0.1,
      restingECG: "Normal",
      stSlope: "Up",
    },
    workflow: {
      status: "Cerrado",
      nextRole: "coordinacion",
      currentTask: "Inspeccionar el historial completo y cómo se cerró el caso.",
      primaryActionLabel: "Ver cierre",
      timeline: [
        {
          id: "evt-pac-402-1",
          title: "Triaje completado",
          by: "Enfermería",
          note: "Ingreso sin anomalías.",
          completed: true,
          timestamp: seedTimestamp,
        },
        {
          id: "evt-pac-402-2",
          title: "Evaluación médica",
          by: "Médico general",
          note: "Riesgo bajo, se indica control en 90 días.",
          completed: true,
          timestamp: seedTimestamp,
        },
        {
          id: "evt-pac-402-3",
          title: "Caso cerrado",
          by: "Coordinación clínica",
          note: "Se registró el plan preventivo.",
          completed: true,
          timestamp: seedTimestamp,
        },
      ],
    },
    assessment: {
      riskLevel: "Bajo",
      riskProbability: 0.24,
      clinicalSummary: "Caso cerrado por el médico clínico sin necesidad de derivación.",
      topFactors: [
        "Frecuencia cardíaca máxima conservada.",
        "Presión en reposo dentro de rango.",
        "Ausencia de angina por ejercicio.",
      ],
      clinicianDisposition: "Cerrar con control",
      clinicianNotes: "Sin criterios de derivación. Se indica control ambulatorio habitual.",
    },
    metadata: {
      createdAt: seedTimestamp,
      updatedAt: seedTimestamp,
    },
  },
];
